<?php

$prefix = danupe()->plugin('user', 'admin')->getPrefix();
return [
    'middlewares' => [
        'auth' => 'Danupe\Plugin\User\Middlewares\AuthMiddleware',
    ],

    'language' => [
        'en' => [
            'auth.login_required' => 'Please log in first.',
            'auth.forbidden' => 'You are not allowed to access this resource.',
            'auth.error_403' => 'Access denied',
            'navigation.dashboard' => 'Dashboard',
            'navigation.users' => 'Users',
            'navigation.users_create' => 'Create User',
        ],
        'de' => [
            'auth.login_required' => 'Bitte zuerst einloggen.',
            'auth.forbidden' => 'Du hast keine Berechtigung für diese Ressource.',
            'auth.error_403' => 'Zugriff verweigert',
            'navigation.dashboard' => 'Übersicht',
            'navigation.users' => 'Benutzer',
            'navigation.users_create' => 'Benutzer anlegen',
        ],
    ],

    'navigation' => [
        '/' . $prefix . '/dashboard' => ['title' => 'navigation.dashboard', 'icon' => 'fa fa-home', 'sort' => 1, 'parent' => '', 'roles' => ['editor','user','admin'], 'translate' => true],
        '/' . $prefix . '/users' => ['title' => 'navigation.users', 'icon' => 'fa fa-users', 'sort' => 100, 'parent' => '', 'roles' => ['admin'], 'translate' => true],
        '/' . $prefix . '/users/create' => ['title' => 'navigation.users_create', 'icon' => 'fa fa-users', 'sort' => 101, 'parent' => '/' . $prefix . '/users', 'roles' => ['admin'], 'translate' => true],
    ],
    'routes' => [
        '/login' => [
            'controller' => 'Danupe\Plugin\User\Controllers\HomeController',
            'action' => 'login',
            'method' => 'GET',
            'middlewares' => [],
            'roles' => ['guest'],
        ],
        '/logout' => [
            'controller' => 'Danupe\Plugin\User\Controllers\AuthController',
            'action' => 'logout_action',
            'method' => 'GET',
            'middlewares' => ['auth'],
            'roles' => ['user', 'admin', 'editor'],
        ],
        '/' . $prefix . '/js/littleBigTable.js' => [
            'controller' => 'Danupe\Core\Classes\AssetController',
            'action' => 'load',
            'method' => 'GET',
            'middlewares' => [],
            'roles' => ['guest'],
            'path' => danupe()->path()->plugin('plugin-user') . '/src/views/assets/js/littleBigTable.js',
            'type' => 'javascript',
        ],
        '/' . $prefix . '/js/charts-bars.js' => [
            'controller' => 'Danupe\Core\Classes\AssetController',
            'action' => 'load',
            'method' => 'GET',
            'middlewares' => [],
            'roles' => ['guest'],
            'path' => danupe()->path()->plugin('plugin-user') . '/src/views/assets/js/charts-bars.js',
            'type' => 'javascript',
        ],
        '/' . $prefix . '/js/charts-lines.js' => [
            'controller' => 'Danupe\Core\Classes\AssetController',
            'action' => 'load',
            'method' => 'GET',
            'middlewares' => [],
            'roles' => ['guest'],
            'path' => danupe()->path()->plugin('plugin-user') . '/src/views/assets/js/charts-lines.js',
            'type' => 'javascript',
        ],
        '/' . $prefix . '/js/charts-pie.js' => [
            'controller' => 'Danupe\Core\Classes\AssetController',
            'action' => 'load',
            'method' => 'GET',
            'middlewares' => [],
            'roles' => ['guest'],
            'path' => danupe()->path()->plugin('plugin-user') . '/src/views/assets/js/charts-pie.js',
            'type' => 'javascript',
        ],
        '/' . $prefix . '/js/focus-trap.js' => [
            'controller' => 'Danupe\Core\Classes\AssetController',
            'action' => 'load',
            'method' => 'GET',
            'middlewares' => [],
            'roles' => ['guest'],
            'path' => danupe()->path()->plugin('plugin-user') . '/src/views/assets/js/focus-trap.js',
            'type' => 'javascript',
        ],
        '/' . $prefix . '/js/init-alpine.js' => [
            'controller' => 'Danupe\Core\Classes\AssetController',
            'action' => 'load',
            'method' => 'GET',
            'middlewares' => [],
            'roles' => ['guest'],
            'path' => danupe()->path()->plugin('plugin-user') . '/src/views/assets/js/init-alpine.js',
            'type' => 'javascript',
        ],
        '/' . $prefix . '/css/tailwind.css' => [
            'controller' => 'Danupe\Core\Classes\AssetController',
            'action' => 'load',
            'method' => 'GET',
            'middlewares' => [],
            'roles' => ['guest'],
            'path' => danupe()->path()->plugin('plugin-user') . '/src/views/assets/css/tailwind.css',
            'type' => 'css',
        ],
        '/' . $prefix . '/css/tailwind.output.css' => [
            'controller' => 'Danupe\Core\Classes\AssetController',
            'action' => 'load',
            'method' => 'GET',
            'middlewares' => [],
            'roles' => ['guest'],
            'path' => danupe()->path()->plugin('plugin-user') . '/src/views/assets/css/tailwind.output.css',
            'type' => 'css',
        ],
        '/' . $prefix . '/login_post' => [
            'controller' => 'Danupe\Plugin\User\Controllers\AuthController',
            'action' => 'login_post',
            'method' => 'POST',
            'middlewares' => [],
            'roles' => ['guest'],
        ],
        '/' . $prefix .'/' => [
            'controller' => 'Danupe\Plugin\User\Controllers\HomeController',
            'action' => 'dashboard',
            'method' => 'GET',
            'middlewares' => ['auth'],
            'roles' => ['editor', 'user', 'admin'],
        ],
        '/' . $prefix  => [
            'controller' => 'Danupe\Plugin\User\Controllers\HomeController',
            'action' => 'dashboard',
            'method' => 'GET',
            'middlewares' => ['auth'],
            'roles' => ['editor', 'user', 'admin'],
        ],
        '/' . $prefix . '/dashboard' => [
            'controller' => 'Danupe\Plugin\User\Controllers\HomeController',
            'action' => 'dashboard',
            'method' => 'GET',
            'middlewares' => ['auth'],
            'roles' => ['editor', 'user', 'admin'],
        ],
        '/' . $prefix . '/users' => [
            'controller' => 'Danupe\Plugin\User\Controllers\UserController',
            'action' => 'index',
            'middlewares' => ['auth'],
            'method' => 'GET',
            'roles' => ['user', 'admin'],
        ],
        '/' . $prefix . '/users/table' => [
            'controller' => 'Danupe\Plugin\User\Controllers\UserController',
            'action' => 'table',
            'middlewares' => ['auth'],
            'method' => 'GET',
            'roles' => ['user', 'admin'],
        ],
        '/' . $prefix . '/users/create' => [
            'controller' => 'Danupe\Plugin\User\Controllers\UserController',
            'action' => 'create',
            'middlewares' => ['auth'],
            'method' => 'GET',
            'roles' => ['user', 'admin'],
        ],
        '/' . $prefix . '/users/edit/{id}' => [
            'controller' => 'Danupe\Plugin\User\Controllers\UserController',
            'action' => 'edit',
            'middlewares' => ['auth'],
            'method' => 'GET',
            'roles' => ['user', 'admin'],
        ],
        '/' . $prefix . '/users/create_post' => [
            'controller' => 'Danupe\Plugin\User\Controllers\UserController',
            'action' => 'create_post',
            'middlewares' => ['auth'],
            'method' => 'POST',
            'roles' => ['user', 'admin'],
        ],
        '/' . $prefix . '/users/update_post' => [
            'controller' => 'Danupe\Plugin\User\Controllers\UserController',
            'action' => 'update_post',
            'middlewares' => ['auth'],
            'method' => 'POST',
            'roles' => ['user', 'admin'],
        ],
        '/' . $prefix . '/users/delete_post' => [
            'controller' => 'Danupe\Plugin\User\Controllers\UserController',
            'action' => 'delete_post',
            'middlewares' => ['auth'],
            'method' => 'POST',
            'roles' => ['user', 'admin'],
        ],
    ],
];
